### PR TITLE
Add ArabicSavior Plugin 

### PR DESCRIPTION
**Pull request by fairbird**
This plugin for fix Arabic language.

### CODE REVIEW

**Comment by persianpros** [comment]
This is wrong, as I wrote in our private section you have to squash and merge not normal merge.

**Comment by fairbird** [comment]
How to do squash ?! in which button ?!

**Comment by persianpros** [comment]
I just restored your branch, create another PR and click on the arrow beside merge button and choose the second option which is squash and merge :+1:

**Comment by fairbird** [comment]
Ok... Understood
Thank you

**Pull request merged**
